version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:cached
    ports:
      - 8081:8081
    environment:
      MYSQL_DATABASE: hoge
    networks:
      - container-networks

networks:
  # default:
  #   external:
  #     name: microservice
  container-networks:
    name: microservice