version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:cached
    ports:
      - 50051:50051
    networks:
      - container-networks
    environment:
      - GRPC_SERVER_PORT=50051

networks:
  default:
    external:
      name: microservices
  container-networks:
    name: microservices