version: "3"
services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:cached
    ports:
      - 50051:50051
    networks:
      - container-networks
    environment:
      - GRPC_SERVER_PORT=50051

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: finder0501
      MYSQL_DATABASE: microservices_user_development
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./infrastructure/mysql:/docker-entrypoint-initdb.d
    ports:
      - '13306:3306'

networks:
  default:
    external:
      name: microservices
  container-networks:
    name: microservices